FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app
COPY ./target/user-managment-energy-system-0.0.1-SNAPSHOT.jar /app

EXPOSE 8081

CMD ["java", "-jar", "user-managment-energy-system-0.0.1-SNAPSHOT.jar"]