FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app
COPY ./target/device-managment-energy-system-0.0.1-SNAPSHOT.jar /app
EXPOSE 8082

CMD ["java", "-jar", "device-managment-energy-system-0.0.1-SNAPSHOT.jar"]